### ISSUE TITLE
Unable to unzip the output of the test-zip-starter

### ISSUE THREAD

**Issue by ChaiBapchya** [edgi-govdata-archiving/zip-starter#7]
Followed the steps outlined in the README.md of the zip-starter repo.
Output test-zip-starter.zip was generated

In order to probe further into the zip file contents,
I tried to unzip / extract it in 2 ways
Using Archive Manager of Fedora
Via Commandline (using Unzip utility - `dnf install unzip`)

`$  unzip test-zip-starter.zip `
``` 
Archive:  test-zip-starter.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of test-zip-starter.zip or
        test-zip-starter.zip.zip, and cannot find test-zip-starter.zip.ZIP, period.
```

Server side

`$ ./zip-starter`
```
zip-starter server starting on port  3000
POST - 2017-03-18 22:03:44.512161773 +0530 IST - /
Bad Content-Type: 'application/x-www-form-urlencoded'
```

**Comment by michardy** [comment]
I was able to fix the problem by amending the test curl command to:
``` bash
curl -H "Content-Type: application/json" -d "{ \"uuid\" : \"test-zip-starter\", \"url\" : \"http://www.epa.gov\"}" http://localhost:3000 > test-zip-starter.zip
```
It appears to be caused because you are submitting JSON but curl defaults in some cases to submitting `Content-Type: 'application/x-www-form-urlencoded'`.  The application detects that it is not being sent JSON and errors.
