### ISSUE TITLE
Status of this repo?

### ISSUE THREAD

**Issue by dcwalk** [edgi-govdata-archiving/zip-starter#8]
@b5 Could you update on the status of this repo? I'm just realizing that we don't have a clear picture anywhere (anymore) about how all the different event repos fit together.

My understanding is we've moved away from referencing this repo as zip-starter was integrated, but I don't know if this code is in sync with that feature...?

**Comment by b5** [comment]
This code is still very much in use. It's what currently powers download zip starter button in the app. If it's cluttering up the edgi page we could try to find a new home for it. would that help?

**Comment by dcwalk** [comment]
I'm not worried about clutter! I just want to make sure that we accurately keep track of all this stuff, I'll clean up the overview repo readme a bit. Thanks!
